# CSI3007-ADVANCED PYTHON PROGRAMMING
# LAB NO : 13
# NAME:VARSHITHA.V
# REG.NO:22MID0105


In [4]:
import numpy as np
np.vander(np.linspace(0,2,5),2) #vander matrix increasing and decreasing power #(0,0.5,1,1.5,2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [6]:
np.vander((1,2,3,4),3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

# NUMPY MODULE IN PYTHON

# np.array()
# Creates an N-dimensional array from a Python list or tuple. This is the most fundamental way to create a NumPy array.



In [8]:
import numpy as np

# Create a 1-D array
my_list = [1, 2, 3, 4, 5]
array1d = np.array(my_list)
print("1-D Array:", array1d)

# Create a 2-D array
my_nested_list = [[1, 2, 3], [4, 5, 6]]
array2d = np.array(my_nested_list)
print("\n2-D Array:\n", array2d)

1-D Array: [1 2 3 4 5]

2-D Array:
 [[1 2 3]
 [4 5 6]]


# np.eye()
# Creates a 2-D array with ones on the main diagonal and zeros elsewhere. This is known as an identity matrix, which is crucial in linear algebra.

In [9]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# Create a 4x5 matrix with the diagonal shifted
shifted_matrix = np.eye(4, 5, k=1)
print("\nShifted Matrix:\n", shifted_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Shifted Matrix:
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# np.linspace()
# Generates an array of a specified number of evenly spaced values over a given interval.

In [10]:
import numpy as np

# Create 5 numbers from 0 to 10 (inclusive)
evenly_spaced = np.linspace(0, 10, 5)
print("Evenly spaced array:\n", evenly_spaced)

Evenly spaced array:
 [ 0.   2.5  5.   7.5 10. ]


# np.arange()
# Generates an array with values from a given range, similar to Python's built-in range() but returns an array instead of a list. You can specify a start, stop, and step size.

In [11]:
import numpy as np

# Create an array from 0 to 9 with a step of 1
range_array = np.arange(10)
print("Array from range(10):\n", range_array)

# Create an array from 5 to 15 with a step of 2
stepped_array = np.arange(5, 16, 2)
print("\nArray with step of 2:\n", stepped_array)

Array from range(10):
 [0 1 2 3 4 5 6 7 8 9]

Array with step of 2:
 [ 5  7  9 11 13 15]


# np.zeros()-Creates a new array of a given shape and fills it with zeros

In [12]:
import numpy as np

# Create a 1-D array of 5 zeros
zeros_1d = np.zeros(5)
print("1-D array of zeros:\n", zeros_1d)

# Create a 2x3 array of zeros
zeros_2d = np.zeros((2, 3))
print("\n2x3 array of zeros:\n", zeros_2d)

1-D array of zeros:
 [0. 0. 0. 0. 0.]

2x3 array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


# np.random()
# The np.random module contains many functions for generating random numbers. A common one is np.random.rand() for a uniform distribution.

In [13]:
import numpy as np

# Generate a 1-D array of 4 random floats between 0 and 1
random_array = np.random.rand(4)
print("Random 1-D array:", random_array)

# Generate a 2x3 array of random floats
random_2d_array = np.random.rand(2, 3)
print("\nRandom 2x3 array:\n", random_2d_array)

Random 1-D array: [0.64296053 0.44639497 0.06691361 0.47037053]

Random 2x3 array:
 [[0.82652621 0.5108141  0.10903767]
 [0.50126251 0.4173411  0.35688056]]


# np.vander()
# Generates a Vandermonde matrix from a 1-D input array. The columns of the output are decreasing powers of the input vector.

In [14]:
import numpy as np

# Create a Vandermonde matrix from a 1-D array
input_array = np.array([1, 2, 3, 4])
vander_matrix = np.vander(input_array)
print("Vandermonde matrix:\n", vander_matrix)

# Create a Vandermonde matrix with a specific number of columns
vander_subset = np.vander(input_array, 3)
print("\nVandermonde matrix with 3 columns:\n", vander_subset)

Vandermonde matrix:
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]

Vandermonde matrix with 3 columns:
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


# Vander with linspace

In [19]:
import numpy as np

# Step 1: Create an evenly spaced array using np.linspace()
# This creates an array of 5 numbers from 0 to 4
x = np.linspace(0, 4, 5)
print("The input array is:\n", x)

# Step 2: Use np.vander() to create the Vandermonde matrix
# The code below takes the array 'x' and generates a matrix
# where each row consists of the decreasing powers of the
# corresponding element from 'x'.
vander_matrix = np.vander(x)
print("\nThe Vandermonde matrix is:\n", vander_matrix)

# You can also specify the number of columns (N) you want.
# Here, we create a matrix with 3 columns.
vander_subset = np.vander(x, N=3)
print("\nThe Vandermonde matrix with 3 columns is:\n", vander_subset)

The input array is:
 [0. 1. 2. 3. 4.]

The Vandermonde matrix is:
 [[  0.   0.   0.   0.   1.]
 [  1.   1.   1.   1.   1.]
 [ 16.   8.   4.   2.   1.]
 [ 81.  27.   9.   3.   1.]
 [256.  64.  16.   4.   1.]]

The Vandermonde matrix with 3 columns is:
 [[ 0.  0.  1.]
 [ 1.  1.  1.]
 [ 4.  2.  1.]
 [ 9.  3.  1.]
 [16.  4.  1.]]


# np.ones() - creates a new NumPy array of a specified shape, filled with the value one.

In [15]:
import numpy as np

# Create a 1-D array of 5 ones
ones_1d = np.ones(5)
print("1-D array of ones:\n", ones_1d)

# Create a 2x3 array of ones
ones_2d = np.ones((2, 3))
print("\n2x3 array of ones:\n", ones_2d)

# Create a 2x3 array of ones with an integer data type
ones_int = np.ones((2, 3), dtype=int)
print("\n2x3 integer array of ones:\n", ones_int)

1-D array of ones:
 [1. 1. 1. 1. 1.]

2x3 array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

2x3 integer array of ones:
 [[1 1 1]
 [1 1 1]]


In [ ]:
np.indices()
1. Two-Dimensional Grid

In [16]:
import numpy as np

# Create a grid of indices for a 2x3 shape
indices_2d = np.indices((2, 3))

print("Grid of indices for a 2x3 array:\n")
print(indices_2d)
print("\nShape of the output:", indices_2d.shape)

Grid of indices for a 2x3 array:

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]

Shape of the output: (2, 2, 3)


In [ ]:
# 2. Three-Dimensional Grid

In [17]:
import numpy as np

# Create a grid of indices for a 2x2x2 shape
indices_3d = np.indices((2, 2, 2))

print("Grid of indices for a 2x2x2 array:\n")
print(indices_3d)

print("\nShape of the output:", indices_3d.shape)

Grid of indices for a 2x2x2 array:

[[[[0 0]
   [0 0]]

  [[1 1]
   [1 1]]]


 [[[0 0]
   [1 1]]

  [[0 0]
   [1 1]]]


 [[[0 1]
   [0 1]]

  [[0 1]
   [0 1]]]]

Shape of the output: (3, 2, 2, 2)


In [2]:
import numpy as np

# Create a 2D array for demonstrationimport numpy as np

# Create a 2D array for demonstration
my_array = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8], 
                     [9, 10, 11, 12]])

# Get the number of dimensions (axes)
dimensions = my_array.ndim
print("Number of dimensions (ndim):", dimensions)

# Get the total number of elements in the array
total_elements = my_array.size
print("Total number of elements (size):", total_elements)

# Get the shape (dimensions) of the array as a tuple
array_shape = my_array.shape
print("Shape of the array (shape):", array_shape)
my_array = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8], 
                     [9, 10, 11, 12]])

# Get the number of dimensions (axes)
dimensions = my_array.ndim
print("Number of dimensions (ndim):", dimensions)

# Get the total number of elements in the array
total_elements = my_array.size
print("Total number of elements (size):", total_elements)

# Get the shape (dimensions) of the array as a tuple
array_shape = my_array.shape
print("Shape of the array (shape):", array_shape)

Number of dimensions (ndim): 2
Total number of elements (size): 12
Shape of the array (shape): (3, 4)
